name: Tests

on:
  # Runt test when pushing to main branch.
  push:
    branches: [main]
  # Run for any PRs.
  pull_request:

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          apt update && apt install -y libcurl4
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov[toml]
          pip install sh

      - name: List dependencies
        run: |
          python -m pip list

      - name: Run tests and collect coverage
        run: |
          wandb login --anonymously ${{ secrets.WANDB_TOKEN }}
          pytest --cov src

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true
